
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muchsin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setTanggal();
        setTanggal1();
        setJam();
        setJam1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtwaktu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        batch = new javax.swing.JTextField();
        siteid_po = new javax.swing.JTextField();
        sitename_po = new javax.swing.JTextField();
        siteid_actual = new javax.swing.JTextField();
        sitename_actual = new javax.swing.JTextField();
        cand = new javax.swing.JTextField();
        lat = new javax.swing.JTextField();
        longg = new javax.swing.JTextField();
        plantower = new javax.swing.JTextField();
        projectid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        lahan = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        timsitac = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        mitra = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tinggitower = new javax.swing.JTextField();
        statuspln = new javax.swing.JTextField();
        sow_implements = new javax.swing.JComboBox<>();
        progress = new javax.swing.JComboBox<>();
        sow_order = new javax.swing.JComboBox<>();
        milestone = new javax.swing.JComboBox<>();
        targetrfi = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txttanggal1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtadmin1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtwaktu1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo 2.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 0, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Mitratel 2.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(120, 0, 240, 100);

        txttanggal.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jPanel2.add(txttanggal);
        txttanggal.setBounds(730, 40, 190, 30);

        jLabel14.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel14.setText("Date  :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(690, 40, 40, 30);

        jLabel15.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel15.setText("User  :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(690, 10, 40, 30);

        txtadmin.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jPanel2.add(txtadmin);
        txtadmin.setBounds(730, 10, 190, 30);

        jLabel20.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel20.setText("Time  :");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(690, 70, 40, 30);

        txtwaktu.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jPanel2.add(txtwaktu);
        txtwaktu.setBounds(730, 70, 190, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 110);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel2.setText("Project ID");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 110, 30);

        jLabel4.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel4.setText("Site ID PO");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 60, 110, 30);

        jLabel5.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel5.setText("Site Name PO");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 100, 130, 30);

        jLabel6.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel6.setText("Site ID Actual");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 140, 140, 30);

        jLabel7.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel7.setText("Site Name Actual");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 180, 150, 30);

        jLabel8.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel8.setText("Cand");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 220, 80, 30);

        jLabel9.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel9.setText("Lat");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 260, 70, 30);

        jLabel10.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel10.setText("Long");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 300, 80, 30);

        jLabel11.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel11.setText("Alamat");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 340, 90, 30);

        jLabel12.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel12.setText("Plan Tower");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 470, 120, 30);

        jLabel13.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel13.setText("Batch");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 510, 80, 30);

        batch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(batch);
        batch.setBounds(150, 510, 290, 30);

        siteid_po.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(siteid_po);
        siteid_po.setBounds(150, 60, 290, 30);

        sitename_po.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(sitename_po);
        sitename_po.setBounds(150, 100, 290, 30);

        siteid_actual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(siteid_actual);
        siteid_actual.setBounds(150, 140, 290, 30);

        sitename_actual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(sitename_actual);
        sitename_actual.setBounds(150, 180, 290, 30);

        cand.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(cand);
        cand.setBounds(150, 220, 290, 30);

        lat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(lat);
        lat.setBounds(150, 260, 290, 30);

        longg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(longg);
        longg.setBounds(150, 300, 290, 30);

        plantower.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(plantower);
        plantower.setBounds(150, 470, 290, 30);

        projectid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(projectid);
        projectid.setBounds(150, 20, 290, 30);

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(150, 340, 290, 120);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 120, 450, 550);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel36.setText("Progress");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(20, 380, 100, 30);

        nohp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(nohp);
        nohp.setBounds(150, 140, 320, 30);

        jLabel30.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel30.setText("No HP");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(20, 140, 90, 30);

        jLabel28.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel28.setText("Mitra");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(20, 60, 80, 30);

        jLabel32.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel32.setText("SoW Order");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(20, 220, 120, 30);

        area.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(area);
        area.setBounds(150, 20, 320, 30);

        lahan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(lahan);
        lahan.setBounds(150, 180, 320, 30);

        jLabel29.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel29.setText("Tim SITAC");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(20, 100, 110, 30);

        timsitac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(timsitac);
        timsitac.setBounds(150, 100, 320, 30);

        jLabel39.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel39.setText("Target RFI");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(20, 460, 110, 30);

        jLabel34.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel34.setText("Tinggi Tower");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(20, 300, 130, 30);

        jLabel27.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel27.setText("Area");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(20, 20, 80, 30);

        jLabel33.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel33.setText("SoW Implements");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(20, 260, 150, 30);

        mitra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(mitra);
        mitra.setBounds(150, 60, 320, 30);

        jLabel31.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel31.setText("Lahan");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(20, 180, 90, 30);

        jLabel35.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel35.setText("Milestone");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(20, 340, 110, 30);

        jLabel38.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jLabel38.setText("Status PLN");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(20, 420, 110, 30);

        tinggitower.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(tinggitower);
        tinggitower.setBounds(150, 300, 320, 30);

        statuspln.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel4.add(statuspln);
        statuspln.setBounds(150, 420, 320, 30);

        sow_implements.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "B2S", "Collo", "Combat", "MCP", "Mini Macro", "TDF" }));
        jPanel4.add(sow_implements);
        sow_implements.setBounds(150, 260, 320, 30);

        progress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01. Proposed ReNom", "02. Survey", "03. Re-Survey", "04. Rehunting", "05. Validasi Cand", "06. Nego Harga", "07. IW", "08. Rekom LURCAM", "09. Perijinan", "10. Soil Test/Hammer Test", "11. Design", "12. RFC", "13. Site Opening", "14. Galian", "15. Borepile", "16. Pembesian", "17. Cor & Curing", "18. Install Pondasi", "19. Tower/Pole Erection", "20. BF, Tray, ME & DAS", "21. CME Done Wait Power", "22. RFI", "23. Wait IP OLO" }));
        jPanel4.add(progress);
        progress.setBounds(150, 380, 320, 30);

        sow_order.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "B2S", "Core", "MCP", "Mini Macro" }));
        jPanel4.add(sow_order);
        sow_order.setBounds(150, 220, 320, 30);

        milestone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01. DROP", "02. CHANG SOW", "03. SIS", "04. SITAC 1", "05. SITAC 2", "06. RFC", "07. CME", "08. RFI", "09. RFI by COMBAT", "10. Wait IP" }));
        jPanel4.add(milestone);
        milestone.setBounds(150, 340, 320, 30);
        jPanel4.add(targetrfi);
        targetrfi.setBounds(150, 460, 320, 30);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel4.add(btnClear);
        btnClear.setBounds(380, 500, 90, 40);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave);
        btnSave.setBounds(280, 500, 90, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(470, 120, 490, 550);

        jTabbedPane1.addTab("Insert Data", jPanel1);

        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo 2.png"))); // NOI18N
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 0, 100, 100);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Mitratel 2.png"))); // NOI18N
        jPanel6.add(jLabel17);
        jLabel17.setBounds(120, 0, 240, 100);

        txttanggal1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jPanel6.add(txttanggal1);
        txttanggal1.setBounds(730, 40, 190, 30);

        jLabel18.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel18.setText("Date  :");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(690, 40, 40, 30);

        jLabel19.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel19.setText("User  :");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(690, 10, 40, 30);

        txtadmin1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jPanel6.add(txtadmin1);
        txtadmin1.setBounds(730, 10, 190, 30);

        jLabel21.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel21.setText("Time  :");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(690, 70, 40, 30);

        txtwaktu1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jPanel6.add(txtwaktu1);
        txtwaktu1.setBounds(730, 70, 190, 30);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 970, 110);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 950, 200);

        jTabbedPane1.addTab("Tabel", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 980, 710);

        setBounds(0, 0, 990, 744);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user1 = Login.user;
        txtadmin.setText(user1);
        String user2 = Login.user;
        txtadmin1.setText(user2);
    }//GEN-LAST:event_formWindowOpened

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            String SQL = "INSERT INTO tb_sitelist (projectid,siteid_po,sitename_po,siteid_actual,sitename_actual,cand,lat,longg,alamat,plantower,batch,area,mitra,timsitac,nohp,lahan,sow_order,sow_implements,tinggitower,milestone,progress,statuspln,targetrfi)"
            + "VALUES('"+projectid.getText()+"','"+siteid_po.getText()+"','"+sitename_po.getText()+"','"+siteid_actual.getText()+"','"+sitename_actual.getText()+"','"+cand.getText()+"','"+lat.getText()+"','"+longg.getText()+"','"+alamat.getText()+"','"+plantower.getText()+"','"+batch.getText()+"','"+area.getText()+"','"+mitra.getText()+"','"+timsitac.getText()+"','"+nohp.getText()+"','"+lahan.getText()+"','"+sow_order.getSelectedItem()+"','"+sow_implements.getSelectedItem()+"','"+tinggitower.getText()+"','"+milestone.getSelectedItem()+"','"+progress.getSelectedItem()+"','"+statuspln.getText()+"','"+targetrfi.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil dimasukkan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dimasukkan", "Coba Lagi", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        projectid.setText("");
        siteid_po.setText("");
        sitename_po.setText("");
        siteid_actual.setText("");
        sitename_actual.setText("");
        cand.setText("");
        lat.setText("");
        longg.setText("");
        alamat.setText("");
        plantower.setText("");
        batch.setText("");
        area.setText("");
        mitra.setText("");
        timsitac.setText("");
        nohp.setText("");
        lahan.setText("");
        sow_order.setSelectedItem("-");
        sow_implements.setSelectedItem("-");
        tinggitower.setText("");
        milestone.setSelectedItem("-");
        progress.setSelectedItem("-");
        statuspln.setText("");
        targetrfi.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void setTanggal(){
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd MMMM yyyy");
        txttanggal.setText(kal.format(now));
    }
    
    private void setTanggal1(){
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd MMMM yyyy");
        txttanggal1.setText(kal.format(now));
    }
    
    public final void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "",nol_detik = "";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                txtwaktu.setText(jam+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    
    public final void setJam1(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "",nol_detik = "";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                txtwaktu1.setText(jam+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField area;
    private javax.swing.JTextField batch;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField cand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lahan;
    private javax.swing.JTextField lat;
    private javax.swing.JTextField longg;
    private javax.swing.JComboBox<String> milestone;
    private javax.swing.JTextField mitra;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField plantower;
    private javax.swing.JComboBox<String> progress;
    private javax.swing.JTextField projectid;
    private javax.swing.JTextField siteid_actual;
    private javax.swing.JTextField siteid_po;
    private javax.swing.JTextField sitename_actual;
    private javax.swing.JTextField sitename_po;
    private javax.swing.JComboBox<String> sow_implements;
    private javax.swing.JComboBox<String> sow_order;
    private javax.swing.JTextField statuspln;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField targetrfi;
    private javax.swing.JTextField timsitac;
    private javax.swing.JTextField tinggitower;
    private javax.swing.JLabel txtadmin;
    private javax.swing.JLabel txtadmin1;
    private javax.swing.JLabel txttanggal;
    private javax.swing.JLabel txttanggal1;
    private javax.swing.JLabel txtwaktu;
    private javax.swing.JLabel txtwaktu1;
    // End of variables declaration//GEN-END:variables
}
